[2021-08-16 12:29:34,260: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 12:29:35,469: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 12:29:38,485: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 12:29:43,506: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 12:29:50,534: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 12:29:59,571: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 12:30:10,619: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 12:30:23,663: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 12:30:38,718: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 12:30:55,765: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 12:31:14,819: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 12:31:35,873: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 12:31:58,933: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 12:32:23,992: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 12:32:51,062: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 12:33:20,140: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2021-08-16 12:33:51,221: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:34:24,285: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:34:57,372: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:35:30,444: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:36:03,514: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:36:36,598: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:37:09,684: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:37:42,756: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:38:15,955: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:38:49,133: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:39:22,324: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:39:55,531: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:40:28,696: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:41:01,912: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:41:35,132: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:42:08,339: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:42:41,563: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:43:14,780: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:15:46,605: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:39:39,132: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:40:12,383: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:40:45,447: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:42:43,772: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 14:42:44,869: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 14:42:47,882: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 14:42:52,898: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 14:42:59,924: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 14:43:08,953: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 14:43:19,992: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 14:43:33,031: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 14:43:48,071: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 14:44:05,097: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 14:44:24,138: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 14:44:45,192: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 14:45:08,247: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 14:45:33,300: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 14:46:00,371: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 14:46:29,432: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2021-08-16 14:47:09,927: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 14:47:11,029: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 14:47:14,037: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 14:47:19,061: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 14:47:26,080: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 14:47:35,102: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 14:47:46,134: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 14:47:59,172: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 14:48:14,219: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 14:48:31,266: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 14:48:50,305: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 14:49:11,359: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 14:49:34,415: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 14:49:59,479: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 14:50:26,561: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 14:50:47,078: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2021-08-16 14:50:47,099: INFO/MainProcess] mingle: searching for neighbors
[2021-08-16 14:50:48,147: INFO/MainProcess] mingle: sync with 1 nodes
[2021-08-16 14:50:48,148: INFO/MainProcess] mingle: sync complete
[2021-08-16 14:50:48,176: WARNING/MainProcess] /Users/i351537/Desktop/Intuit-Craft/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-08-16 14:50:48,177: INFO/MainProcess] w2@C02XC0Y9JGH5 ready.
[2021-08-16 14:50:49,234: INFO/MainProcess] sync with w3@C02XC0Y9JGH5
[2021-08-16 15:11:30,271: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-08-16 15:19:15,259: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2021-08-16 15:19:15,285: INFO/MainProcess] mingle: searching for neighbors
[2021-08-16 15:19:16,333: INFO/MainProcess] mingle: sync with 1 nodes
[2021-08-16 15:19:16,333: INFO/MainProcess] mingle: sync complete
[2021-08-16 15:19:16,355: WARNING/MainProcess] /Users/i351537/Desktop/Intuit-Craft/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-08-16 15:19:16,356: INFO/MainProcess] w2@C02XC0Y9JGH5 ready.
[2021-08-16 15:19:17,682: INFO/MainProcess] sync with w3@C02XC0Y9JGH5
[2021-08-16 15:19:39,628: INFO/MainProcess] Task game_engine.tasks.add[4f093413-c04d-43b9-86fa-8507f4dad99c] received
[2021-08-16 15:20:08,275: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-08-16 21:30:33,158: INFO/MainProcess] missed heartbeat from w1@C02XC0Y9JGH5
[2021-08-16 21:30:33,204: INFO/MainProcess] missed heartbeat from w3@C02XC0Y9JGH5
