[2021-08-16 12:29:36,164: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 12:29:37,303: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 12:29:40,330: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 12:29:45,363: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 12:29:52,388: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 12:30:01,417: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 12:30:12,456: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 12:30:25,526: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 12:30:40,597: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 12:30:57,639: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 12:31:16,699: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 12:31:37,744: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 12:32:00,793: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 12:32:25,859: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 12:32:52,924: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 12:33:21,982: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2021-08-16 12:33:53,066: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:34:26,147: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:34:59,234: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:35:32,297: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:36:05,380: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:36:38,456: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:37:11,520: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:37:44,589: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:38:17,795: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:38:50,973: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:39:24,154: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:39:57,322: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:40:30,520: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:41:03,684: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:41:36,877: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:42:10,118: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:42:43,297: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 12:43:16,508: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:15:48,603: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:39:41,024: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:40:14,340: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:40:47,431: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-08-16 14:42:44,777: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 14:42:45,876: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 14:42:48,890: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 14:42:53,907: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 14:43:00,932: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 14:43:09,962: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 14:43:20,988: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 14:43:34,030: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 14:43:49,062: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 14:44:06,090: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 14:44:25,138: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 14:44:46,195: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 14:45:09,250: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 14:45:34,303: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 14:46:01,371: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 14:46:30,436: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2021-08-16 14:47:11,037: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
[2021-08-16 14:47:12,138: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-08-16 14:47:15,150: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-08-16 14:47:20,164: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-08-16 14:47:27,185: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-08-16 14:47:36,215: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-08-16 14:47:47,246: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-08-16 14:48:00,288: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-08-16 14:48:15,330: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-08-16 14:48:32,373: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-08-16 14:48:51,432: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-08-16 14:49:12,502: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-08-16 14:49:35,567: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-08-16 14:50:00,643: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-08-16 14:50:27,733: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-08-16 14:50:49,173: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2021-08-16 14:50:49,191: INFO/MainProcess] mingle: searching for neighbors
[2021-08-16 14:50:50,245: INFO/MainProcess] mingle: sync with 2 nodes
[2021-08-16 14:50:50,246: INFO/MainProcess] mingle: sync complete
[2021-08-16 14:50:50,269: WARNING/MainProcess] /Users/i351537/Desktop/Intuit-Craft/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-08-16 14:50:50,269: INFO/MainProcess] w3@C02XC0Y9JGH5 ready.
[2021-08-16 15:11:30,271: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-08-16 15:19:17,619: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2021-08-16 15:19:17,640: INFO/MainProcess] mingle: searching for neighbors
[2021-08-16 15:19:18,689: INFO/MainProcess] mingle: sync with 2 nodes
[2021-08-16 15:19:18,690: INFO/MainProcess] mingle: sync complete
[2021-08-16 15:19:18,715: WARNING/MainProcess] /Users/i351537/Desktop/Intuit-Craft/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-08-16 15:19:18,715: INFO/MainProcess] w3@C02XC0Y9JGH5 ready.
[2021-08-16 15:20:08,275: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-08-16 15:20:20,410: INFO/MainProcess] Task game_engine.tasks.add[d671d529-083a-4b01-b33a-16e86b41ea5e] received
[2021-08-16 15:37:22,846: INFO/MainProcess] missed heartbeat from w2@C02XC0Y9JGH5
[2021-08-16 15:37:22,919: INFO/MainProcess] missed heartbeat from w1@C02XC0Y9JGH5
[2021-08-16 16:08:10,220: INFO/MainProcess] missed heartbeat from w1@C02XC0Y9JGH5
[2021-08-16 16:08:10,242: INFO/MainProcess] missed heartbeat from w2@C02XC0Y9JGH5
[2021-08-16 21:30:33,091: INFO/MainProcess] missed heartbeat from w2@C02XC0Y9JGH5
[2021-08-16 21:30:33,225: INFO/MainProcess] missed heartbeat from w1@C02XC0Y9JGH5
